/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package apppuntoventa;
import java.awt.Color;
import java.awt.Image;
import java.io.BufferedReader;
import java.io.FileReader;
import java.io.FileWriter;
import java.io.IOException;
import javax.swing.JColorChooser;
import modelos.Producto;
import java.awt.Component;
import java.io.File;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableCellRenderer;

/**
 *
 * @author oziel
 */
public class frmProducto extends javax.swing.JDialog {

    /**
     * Creates new form frmProducto
     */
    public frmProducto(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlPrincipal = new javax.swing.JPanel();
        imgFoto = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblAltaProductos = new javax.swing.JTable();
        btnFoto = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        txtNombre = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        spnCantidad = new javax.swing.JSpinner();
        btnAgregar = new javax.swing.JButton();
        btnAbrir = new javax.swing.JButton();
        btnGuardar = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        txtDescripcion = new javax.swing.JTextArea();
        btnCerrar = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        txtID = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        txtCodigo = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        txtUnitario = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        txtMayoreo = new javax.swing.JTextField();
        btnColor = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        pnlPrincipal.setBackground(new java.awt.Color(204, 204, 204));

        imgFoto.setBackground(new java.awt.Color(153, 204, 255));
        imgFoto.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));

        tblAltaProductos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Foto", "Nombre", "Cantidad", "Precio unitario", "Precio mayoritario"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblAltaProductos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblAltaProductosMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblAltaProductos);

        btnFoto.setText("Agregar Foto");
        btnFoto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFotoActionPerformed(evt);
            }
        });

        jLabel2.setText("Nombre:");

        jLabel3.setText("Cantidad:");

        btnAgregar.setText("Agregar Producto");
        btnAgregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAgregarActionPerformed(evt);
            }
        });

        btnAbrir.setText("Abrir");
        btnAbrir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAbrirActionPerformed(evt);
            }
        });

        btnGuardar.setText("Guardar");
        btnGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuardarActionPerformed(evt);
            }
        });

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/save_icon.png"))); // NOI18N

        jLabel5.setText("Descripcion:");

        txtDescripcion.setColumns(20);
        txtDescripcion.setRows(5);
        jScrollPane2.setViewportView(txtDescripcion);

        btnCerrar.setText("Cerrar");
        btnCerrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCerrarActionPerformed(evt);
            }
        });

        jLabel6.setText("ID:");

        jLabel7.setText("Codigo Producto:");

        jLabel8.setText("Precio Unitario:");

        jLabel9.setText("Precio Mayoreo:");

        btnColor.setText("Cambiar Color");
        btnColor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnColorActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnlPrincipalLayout = new javax.swing.GroupLayout(pnlPrincipal);
        pnlPrincipal.setLayout(pnlPrincipalLayout);
        pnlPrincipalLayout.setHorizontalGroup(
            pnlPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlPrincipalLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlPrincipalLayout.createSequentialGroup()
                        .addGroup(pnlPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1)
                            .addGroup(pnlPrincipalLayout.createSequentialGroup()
                                .addComponent(btnCerrar)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btnColor)))
                        .addContainerGap())
                    .addGroup(pnlPrincipalLayout.createSequentialGroup()
                        .addGroup(pnlPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(imgFoto, javax.swing.GroupLayout.PREFERRED_SIZE, 193, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnFoto, javax.swing.GroupLayout.PREFERRED_SIZE, 193, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(46, 46, 46)
                        .addGroup(pnlPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(pnlPrincipalLayout.createSequentialGroup()
                                .addComponent(jLabel8)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(txtUnitario))
                            .addGroup(pnlPrincipalLayout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(txtNombre))
                            .addGroup(pnlPrincipalLayout.createSequentialGroup()
                                .addComponent(jLabel3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(spnCantidad, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(pnlPrincipalLayout.createSequentialGroup()
                                .addComponent(jLabel5)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(pnlPrincipalLayout.createSequentialGroup()
                                .addComponent(jLabel6)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtID))
                            .addGroup(pnlPrincipalLayout.createSequentialGroup()
                                .addComponent(jLabel7)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtCodigo))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlPrincipalLayout.createSequentialGroup()
                                .addComponent(jLabel9)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(txtMayoreo, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 79, Short.MAX_VALUE)
                        .addGroup(pnlPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(btnAbrir, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnAgregar, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnGuardar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(16, 16, 16)
                        .addComponent(jLabel4)
                        .addGap(51, 51, 51))))
        );
        pnlPrincipalLayout.setVerticalGroup(
            pnlPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlPrincipalLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlPrincipalLayout.createSequentialGroup()
                        .addGroup(pnlPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(txtNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(16, 16, 16)
                        .addGroup(pnlPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(spnCantidad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(28, 28, 28)
                        .addGroup(pnlPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel5)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(14, 14, 14)
                        .addGroup(pnlPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel6)
                            .addComponent(txtID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(pnlPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel7)
                            .addComponent(txtCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(pnlPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel8)
                            .addComponent(txtUnitario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(pnlPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel9)
                            .addComponent(txtMayoreo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(pnlPrincipalLayout.createSequentialGroup()
                        .addComponent(imgFoto, javax.swing.GroupLayout.PREFERRED_SIZE, 188, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnFoto))
                    .addGroup(pnlPrincipalLayout.createSequentialGroup()
                        .addGroup(pnlPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(btnAgregar)
                            .addComponent(jLabel4))
                        .addGap(18, 18, 18)
                        .addComponent(btnAbrir)
                        .addGap(18, 18, 18)
                        .addComponent(btnGuardar)))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(pnlPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnCerrar)
                    .addComponent(btnColor))
                .addContainerGap(24, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlPrincipal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlPrincipal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnCerrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCerrarActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_btnCerrarActionPerformed

    private void btnAgregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAgregarActionPerformed
        // TODO add your handling code here:
        if(rutaArchivo == "" || txtNombre.getText() == "" || Integer.parseInt(spnCantidad.getValue().toString()) == 0 || txtDescripcion.getText() == "" || txtID.getText() == "" || txtCodigo.getText() == "" || txtUnitario.getText() == "" || txtMayoreo.getText() == ""){
            JOptionPane.showMessageDialog(null, "Hay Campos Vacios", "ADVERTENCIA!!!", JOptionPane.WARNING_MESSAGE);
        }else{
            String nombre = txtNombre.getText();
                int cant = Integer.parseInt(spnCantidad.getValue().toString());
                String descrip = txtDescripcion.getText();
                int ID = Integer.parseInt(txtID.getText());
                String code = txtCodigo.getText();
                double pUni = Double.parseDouble(txtUnitario.getText());
                double pMay = Double.parseDouble(txtMayoreo.getText());
        
                JLabel imgLabel = new JLabel();
                Image img = new ImageIcon(rutaArchivo).getImage();
                Image newimg = img.getScaledInstance(150, 150, java.awt.Image.SCALE_SMOOTH);
                ImageIcon imageIcon = new ImageIcon(newimg);
                imgLabel.setIcon(imageIcon);
        
                Negocio.NegocioProducto.lstProductos.add(new Producto(imgLabel.toString(), nombre, cant, descrip, ID, code, pUni, pMay));
        
                DefaultTableModel model=(DefaultTableModel) tblAltaProductos.getModel();
                tblAltaProductos.getColumn("Foto").setCellRenderer(new labelRender()); 
                model.addRow(new Object[]{imgLabel, nombre, cant, pUni, pMay});
                updateRowHeights();
                imgFoto.setIcon(null);
                txtNombre.setText("");
                spnCantidad.setValue(0);
                txtDescripcion.setText("");
                txtID.setText("");
                txtCodigo.setText("");
                txtUnitario.setText("");
                txtMayoreo.setText("");
        }
        /*try{
            if(rutaArchivo == "" || Integer.parseInt(spnCantidad.getValue().toString()) == 0){
                JOptionPane.showMessageDialog(null, "Hay Campos Vacios", "ADVERTENCIA!!!", JOptionPane.WARNING_MESSAGE);
            }else{
                String nombre = txtNombre.getText();
                int cant = Integer.parseInt(spnCantidad.getValue().toString());
                String descrip = txtDescripcion.getText();
                int ID = Integer.parseInt(txtID.getText());
                String code = txtCodigo.getText();
                double pUni = Double.parseDouble(txtUnitario.getText());
                double pMay = Double.parseDouble(txtMayoreo.getText());
        
                JLabel imgLabel = new JLabel();
                Image img = new ImageIcon(rutaArchivo).getImage();
                Image newimg = img.getScaledInstance(150, 150, java.awt.Image.SCALE_SMOOTH);
                ImageIcon imageIcon = new ImageIcon(newimg);
                imgLabel.setIcon(imageIcon);
        
                Negocio.NegocioProducto.lstProductos.add(new Producto(imgLabel.toString(), nombre, cant, descrip, ID, code, pUni, pMay));
        
                DefaultTableModel model=(DefaultTableModel) tblAltaProductos.getModel();
                tblAltaProductos.getColumn("Foto").setCellRenderer(new labelRender()); 
                model.addRow(new Object[]{imgLabel, nombre, cant, pUni, pMay});
                updateRowHeights();
            }
            
        }catch(Exception e){
            JOptionPane.showMessageDialog(null, "Hay Campos Vacios", "ADVERTENCIA!!!", JOptionPane.WARNING_MESSAGE);
        }*/
        
    }//GEN-LAST:event_btnAgregarActionPerformed

    private void tblAltaProductosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblAltaProductosMouseClicked
        // TODO add your handling code here:
        JTable source = (JTable)evt.getSource();
        int row=source.rowAtPoint(evt.getPoint());
        
        String nombre = Negocio.NegocioProducto.lstProductos.get(row).getNombreProducto();
        
        JOptionPane.showMessageDialog(null, "Nombre: " + nombre);
    }//GEN-LAST:event_tblAltaProductosMouseClicked

    private void btnColorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnColorActionPerformed
        // TODO add your handling code here:
        JColorChooser ventColores = new JColorChooser();
        
        Color color = ventColores.showDialog(null,"Seleccione un color", Color.gray);
        
        //pnlPrincipal.setBackground(color);
        txtNombre.setForeground(color);
        spnCantidad.setBackground(color);
        txtDescripcion.setForeground(color);
        txtID.setForeground(color);
        txtCodigo.setForeground(color);
        txtUnitario.setForeground(color);
        txtMayoreo.setForeground(color);
        tblAltaProductos.setForeground(color);
    }//GEN-LAST:event_btnColorActionPerformed

    private void btnGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardarActionPerformed
        // TODO add your handling code here:
        try{
            if(rutaArchivo == "" || txtNombre.getText() == "" || Integer.parseInt(spnCantidad.getValue().toString()) == 0 || txtDescripcion.getText() == "" || txtID.getText() == "" || txtCodigo.getText() == "" || txtUnitario.getText() == "" || txtMayoreo.getText() == ""){
                JOptionPane.showMessageDialog(null, "Hay Campos Vacios", "ADVERTENCIA!!!", JOptionPane.WARNING_MESSAGE);
            }else{
                String nombre = "";
                JFileChooser file = new JFileChooser();
                file.showSaveDialog(this);
                File guarda = file.getSelectedFile();
            
                if(guarda != null){
                    FileWriter save = new FileWriter(guarda + ".txt");
                    save.write(rutaArchivo + "\n");
                    save.write(txtNombre.getText() + "\n");
                    save.write(spnCantidad.getValue().toString() + "\n");
                    save.write(txtDescripcion.getText() + "\n");
                    save.write(txtID.getText() + "\n");
                    save.write(txtCodigo.getText() + "\n");
                    save.write(txtUnitario.getText() + "\n");
                    save.write(txtMayoreo.getText() + "\n");
                    save.close();
                    JOptionPane.showMessageDialog(null, "El archivo se a guardado Exitosamente", "Informacion", JOptionPane.INFORMATION_MESSAGE);
                }
            }
        }catch(IOException ex){
            JOptionPane.showMessageDialog(null, "Su archivo no se ha guardado", "Advertencia", JOptionPane.WARNING_MESSAGE);
        }
    }//GEN-LAST:event_btnGuardarActionPerformed

    private void btnAbrirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAbrirActionPerformed
        // TODO add your handling code here:
        String aux="";
        String text = "";
        try{
            JFileChooser file = new JFileChooser();
            file.showOpenDialog(this);
            File abre = file.getSelectedFile();
            
            if(abre != null){
                FileReader archivos = new FileReader(abre);
                BufferedReader lee = new BufferedReader(archivos);
                while((aux=lee.readLine()) != null){
                    text += aux + "\n";
                    //JOptionPane.showMessageDialog(null, text);
                    //cajatexto.setText(texto)
                }
                lee.close();
                //JOptionPane.showMessageDialog(null, text);
                String[] nom = text.split("\n");
                rutaArchivo = nom[0];
                Image img = new ImageIcon(nom[0]).getImage();
                Image newimg = img.getScaledInstance(150, 150, java.awt.Image.SCALE_SMOOTH);
                ImageIcon imageIcon = new ImageIcon(newimg);
                imgFoto.setIcon(imageIcon);
                txtNombre.setText(nom[1]);
                spnCantidad.setValue(Integer.parseInt(nom[2]));
                txtDescripcion.setText(nom[3]);
                txtID.setText(nom[4]);
                txtCodigo.setText(nom[5]);
                txtUnitario.setText(nom[6]);
                txtMayoreo.setText(nom[7]);
                
            }
        }catch(IOException ex){
            JOptionPane.showMessageDialog(null, ex + "" + "\nNo se ha encontrado el archivo", "ADVERTENCIA!!!", JOptionPane.WARNING_MESSAGE);
        }catch(Exception ex){
            JOptionPane.showMessageDialog(null, ex + "" + "\nError general", "ADVERTENCIA!!!", JOptionPane.WARNING_MESSAGE);
        }
    }//GEN-LAST:event_btnAbrirActionPerformed

    JFileChooser fc;
    String rutaArchivo = "";
    
    private void btnFotoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFotoActionPerformed
        // TODO add your handling code here:
        fc = new JFileChooser();
        fc.setDialogTitle("Buscar Foto o Imagen");
        
        if (fc.showOpenDialog(this) == JFileChooser.APPROVE_OPTION) {
            rutaArchivo = fc.getSelectedFile().toString();
            File archivo = new File(fc.getSelectedFile().toString());
            
            //rsscalelabel.RSScaleLabel.setScaleLabel(imgFoto, fc.getSelectedFile().toString());
            escalarImagen(rutaArchivo);
        }
    }//GEN-LAST:event_btnFotoActionPerformed

    private void escalarImagen(String urlFile){
        JLabel imgLabel = new JLabel();
        
        //Imagen Origen
        Image img = new ImageIcon(urlFile).getImage();
        
        //Escala imagen
        Image newimg = img.getScaledInstance(150, 150, java.awt.Image.SCALE_SMOOTH);
        ImageIcon imageIcon = new ImageIcon(newimg);
        
        //Asigna a componnete JLabel
        imgFoto.setIcon(imageIcon);
    }
    
    private void updateRowHeights()
    {
      JTable table  =  tblAltaProductos;
      
        for (int row = 0; row < table.getRowCount(); row++)
        {
            int rowHeight = table.getRowHeight();

            for (int column = 0; column < table.getColumnCount(); column++)
            {
                Component comp = table.prepareRenderer(table.getCellRenderer(row, column), row, column);
                rowHeight = Math.max(rowHeight, comp.getPreferredSize().height);
            }

            table.setRowHeight(row, rowHeight);
        }
   }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmProducto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmProducto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmProducto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmProducto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                frmProducto dialog = new frmProducto(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAbrir;
    private javax.swing.JButton btnAgregar;
    private javax.swing.JButton btnCerrar;
    private javax.swing.JButton btnColor;
    private javax.swing.JButton btnFoto;
    private javax.swing.JButton btnGuardar;
    private javax.swing.JLabel imgFoto;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JPanel pnlPrincipal;
    private javax.swing.JSpinner spnCantidad;
    private javax.swing.JTable tblAltaProductos;
    private javax.swing.JTextField txtCodigo;
    private javax.swing.JTextArea txtDescripcion;
    private javax.swing.JTextField txtID;
    private javax.swing.JTextField txtMayoreo;
    private javax.swing.JTextField txtNombre;
    private javax.swing.JTextField txtUnitario;
    // End of variables declaration//GEN-END:variables
}

class labelRender implements TableCellRenderer{

    @Override
    public Component getTableCellRendererComponent(JTable table, Object value, boolean isSelected, boolean hasFocus, int row, int column) {
        //throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
        return (Component)value;
    }
    
}
